name: Deploy Flask Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Optional: Lint code
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5️⃣ Optional: Run tests
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      # 6️⃣ Create .env file
      - name: Create .env file
        run: |
          echo "FLASK_ENV=production" > .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          # Add other environment variables here

      # 7️⃣ Deploy to cPanel via FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./             # root of your repo
          dry-run: false
